name: CI/CD to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps & run tests
        run: |
          npm install
          npm test


      - name: Debug region secret
        run: |
          echo "Region is ${{ secrets.AWS_REGION }}"


      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: me-south-1

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t github-actions/actions-api .

      - name: Tag Docker image
        run: |
          docker tag github-actions/actions-api:latest 104974779468.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/github-actions/actions-api:latest

      - name: Push to ECR
        run: |
          docker push 104974779468.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/github-actions/actions-api:latest


  deploy:
    runs-on: ubuntu-latest   # ✅ use GitHub runner, not amazon-linux
    needs: build-test-push

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Your deployment commands will run here
            ./entrypoint.sh
          
          # <--- THIS IS THE CRITICAL PART --->
          # Forward all necessary secrets and envs to the remote machine's shell
          envs: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
            IMAGE_NAME=${{ env.IMAGE_NAME }}
